
### DO NOT EDIT THIS FILE ###

'''facade - makes reremarkable_lib package easy to refactor

while keeping its api constant'''
from .helpers import set_up_logging
from .reremarkableconfig import get_version
from .Window import Window
