# -*- Mode: Python; coding: utf-8; indent-tabs-mode: nil; tab-width: 4 -*-

### DO NOT EDIT THIS FILE ###

'''facade - makes reremarkable_lib package easy to refactor

while keeping its api constant'''
from . helpers import set_up_logging
from . Window import Window
from . reremarkableconfig import get_version
