
### DO NOT EDIT THIS FILE ###

__all__ = [
    'project_path_not_found',
    'get_data_file',
    'get_data_path',
    ]

# Where your project will look for your data
#(for instance, images and ui files).
__reremarkable_data_directories__ = ['../data', '/usr/share/reremarkable']

import os
import sys

# Add project root to Python path to import version
sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..'))
from version import __version__


class project_path_not_found(Exception):
    """Raised when we can't find the project directory."""


def get_data_file(*path_segments):
    """Get the full path to a data file.

    Returns the path to a file underneath the data directory (as defined by
    `get_data_path`). Equivalent to os.path.join(get_data_path(),
    *path_segments).
    """
    return os.path.join(get_data_path(), *path_segments)


def get_data_path():
    """Retrieve reremarkable data path

    This path is by default <reremarkable_lib_path>/../data/ in trunk
    and /usr/share/reremarkable in an installed version but this path
    is specified at installation time.
    """

    for data_dir in __reremarkable_data_directories__:
        path = os.path.join(
            os.path.dirname(__file__), data_dir)

        abs_data_path = os.path.abspath(path)

        if os.path.exists(abs_data_path):
            return abs_data_path

    raise project_path_not_found


def get_version():
    return __version__
